# fly.toml app configuration file generated for move-cgi-bw on 2025-08-03T21:05:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'move-cgi-bw'
primary_region = 'fra'

[build]
  [build.args]
    API_BASE_URL = 'https://move.fly.dev/api'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
